### Production environment settings

# STS role and target account
Sts.Role: arn:aws:iam::754048514734:role/admin


# VPCs
Config.Vpcs:
  Default:
    Cidr: 192.168.0.0/20
    Domain: dockerproductionaws.org